version: "1.0"

services:
  app:
    container_name: warehouse-microservice
    command: java -jar target/warehouse-service-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - database-warehouse
    volumes:
      - ./:/app/app
    links:
      - database-warehouse
    networks:
      - internal
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672


  database-warehouse:
    image: postgres
    container_name: database-warehouse
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./:/app/
    command: -p 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=warehouse_db
    networks:
      - internal

networks:
  internal:
    name: internal