version: "3.9"

services:
  app:
    container_name: warehouse-microservice
    command: java -jar target/warehouse-service-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - postgres-warehouse
    volumes:
      - ./:/app/app
    links:
      - postgres-warehouse
    networks:
      - internal

  postgres-warehouse:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./:/app/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=warehouse_db
    networks:
      - internal

networks:
  internal:
    name: internal